apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{serviceName}}
  namespace: {{namespace}}
  labels:
    {{labelKey}}: {{labelValue}}
spec:
  hosts:
  - {{host}}
  http:
  - route:
    - destination:
        host: {{newHost}}
        port:
          number: {{port}}
